version: "3.9"

services:
  backend:
    image: ayushdh96/mie_diarization-backend:latest
    ports:
      - "5001:5001"
    working_dir: /app/whisper-diarization

  frontend:
    image: ayushdh96/mie_diarization-frontend:latest
    ports:
      - "5173:5173"
    working_dir: /app/diarization-ui
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]