version: "3.9"

services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "5001:5001"
    working_dir: /app/whisper-diarization
    volumes:
      - ./whisper-diarization:/app/whisper-diarization

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "5173:5173"
    working_dir: /app/diarization-ui
    volumes:
      - ./diarization-ui:/app/diarization-ui
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]